"use client";
import { useMemo, useState } from "react";
import { Archive, Search } from "lucide-react";
import { archivedDocuments } from "@/lib/archived-documents";
import { DocumentField, DocumentSheet } from "./DocumentSheet";
import type { DocumentStatus, DocumentSymbol, ModuleId } from "@/lib/types";
import { useT } from "@/lib/use-t";

export function DocumentArchive({moduleId}:{moduleId:ModuleId}) {
  const t=useT();
  const moduleDocuments=archivedDocuments.filter(item=>item.meta.moduleId===moduleId);
  const [selectedId,setSelectedId]=useState(moduleDocuments[0]?.meta.id??"");
  const [query,setQuery]=useState(""); const [symbol,setSymbol]=useState<"all"|DocumentSymbol>("all"); const [status,setStatus]=useState<"all"|DocumentStatus>("all");
  const filtered=useMemo(()=>moduleDocuments.filter(item=>(symbol==="all"||item.meta.symbol===symbol)&&(status==="all"||item.meta.status===status)&&(!query||`${item.meta.number} ${item.title} ${item.subject} ${item.meta.author} ${item.meta.relatedOrderId??""}`.toLocaleLowerCase("pl").includes(query.toLocaleLowerCase("pl")))),[moduleDocuments,query,status,symbol]);
  const selected=moduleDocuments.find(item=>item.meta.id===selectedId)??filtered[0]??moduleDocuments[0];
  const symbols=[...new Set(moduleDocuments.map(item=>item.meta.symbol))];
  return <div className="p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="flex items-center gap-2 text-[14px] font-bold text-(--color-navy)"><Archive size={17}/> {t("Archiwum dokumentów")} · {t("moduł")} {moduleId}</h2><p className="mt-1 text-[11px] text-(--color-ink-soft)">{t("Dokumenty z ostatnich sześciu miesięcy. Rekordy zatwierdzone pozostają niezmienne; korekty są oznaczone osobnym statusem.")}</p></div><div className="font-mono text-[11px] text-(--color-ink-faint)">{t("W module:")} {moduleDocuments.length} · {t("w całym systemie:")} {archivedDocuments.length}</div></div>
    <div className="mb-3 grid grid-cols-[1fr_180px_180px] gap-2"><label className="flex items-center gap-2 border border-(--color-border-strong) bg-white px-3"><Search size={14} className="text-(--color-ink-faint)"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("Numer, autor, zlecenie lub treść…")} className="h-9 w-full border-0 bg-transparent text-[11.5px] outline-none"/></label><select value={symbol} onChange={e=>setSymbol(e.target.value as "all"|DocumentSymbol)} className="border border-(--color-border-strong) bg-white px-3 text-[11px]"><option value="all">{t("Wszystkie typy")}</option>{symbols.map(item=><option key={item} value={item}>{item}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value as "all"|DocumentStatus)} className="border border-(--color-border-strong) bg-white px-3 text-[11px]"><option value="all">{t("Wszystkie statusy")}</option><option value="zatwierdzony">{t("Zatwierdzone")}</option><option value="skorygowany">{t("Skorygowane")}</option></select></div>
    <div className="grid grid-cols-[360px_1fr] gap-4"><div className="max-h-[650px] overflow-auto border border-(--color-border) bg-white">{filtered.length?filtered.map(item=><button key={item.meta.id} onClick={()=>setSelectedId(item.meta.id)} className={`grid w-full grid-cols-[85px_1fr] border-b p-3 text-left ${selected?.meta.id===item.meta.id?"bg-(--color-steel-light)":"hover:bg-(--color-bg)"}`}><div><div className="font-mono text-[9.5px] text-(--color-ink-faint)">{item.meta.date}</div><span className={`mt-1 inline-block rounded-sm px-1.5 py-0.5 text-[8px] font-bold ${item.meta.status==="skorygowany"?"bg-(--color-status-amber-bg) text-(--color-status-amber)":"bg-(--color-status-green-bg) text-(--color-status-green)"}`}>{t(item.meta.status).toUpperCase()}</span></div><div><div className="font-mono text-[10.5px] font-bold text-(--color-navy)">{item.meta.number}</div><div className="mt-0.5 text-[11px] font-medium">{t(item.subject)}</div><div className="mt-1 text-[9px] text-(--color-ink-faint)">{item.meta.author} {item.meta.relatedOrderId?`· ${item.meta.relatedOrderId}`:""}</div></div></button>):<div className="p-8 text-center text-[11px] text-(--color-ink-faint)">{t("Brak dokumentów dla wybranych filtrów.")}</div>}</div>
      <div>{selected&&<DocumentSheet meta={selected.meta} title={selected.title}><DocumentField label={t("Przedmiot")} value={t(selected.subject)}/><DocumentField label={t("Opis archiwalny")} value={t(selected.summary)}/><DocumentField label={t("Powiązane zlecenie")} value={selected.meta.relatedOrderId??t("Dokument kartotekowy")}/>{selected.sourceDocument&&<DocumentField label={t("Dokument źródłowy")} value={selected.sourceDocument}/>}<DocumentField label={t("Wartość / kwota")} value={selected.amount??t("Nie dotyczy")}/><DocumentField label={t("Integralność")} value={t("Dokument zamknięty · zachowana historia autora i statusu")}/><div className="mt-4 border border-(--color-border) bg-(--color-bg) p-3 text-[10.5px] text-(--color-ink-soft)">{t("Dokument można przeglądać i śledzić do źródła. Ewentualna zmiana wymaga protokołu korekty — oryginalny zapis pozostaje w archiwum.")}</div></DocumentSheet>}</div></div>
  </div>;
}
