"use client";
import { useMemo, useState } from "react";
import { Boxes, Clock3, Factory, Search } from "lucide-react";
import { productionBatches } from "@/lib/production-batches";
import { formatNumber, formatPercent, getProduct } from "@/lib/calculations";
import { DocumentField, DocumentSheet } from "./DocumentSheet";
import type { ProductionBatch } from "@/lib/types";
import { useT, useLang } from "@/lib/use-t";

const statusLabel={zakonczona:"ZAKOŃCZONA",w_realizacji:"W REALIZACJI",wstrzymana:"WSTRZYMANA"};
export function ProductionBatches() {
  const t=useT(); const lang=useLang();
  const [productId,setProductId]=useState("all"); const [status,setStatus]=useState("all"); const [query,setQuery]=useState(""); const [selectedId,setSelectedId]=useState(productionBatches[0]!.id);
  const filtered=useMemo(()=>productionBatches.filter(batch=>(productId==="all"||batch.productId===productId)&&(status==="all"||batch.status===status)&&(!query||`${batch.id} ${batch.productionOrderId} ${batch.materialLot} ${batch.operator}`.toLowerCase().includes(query.toLowerCase()))),[productId,status,query]);
  const selected=productionBatches.find(batch=>batch.id===selectedId)??filtered[0]??productionBatches[0]!;
  const completed=productionBatches.filter(item=>item.status==="zakonczona").length;
  const totalGood=productionBatches.reduce((sum,item)=>sum+item.goodQty,0);
  const totalBad=productionBatches.reduce((sum,item)=>sum+item.badQty,0);
  return <div className="p-5"><div className="mb-4 grid grid-cols-4 gap-3"><Kpi icon={<Boxes size={16}/>} label={t("Szarże w ostatnich 60 dniach")} value={String(productionBatches.length)}/><Kpi icon={<Factory size={16}/>} label={t("Zakończone / aktywne")} value={`${completed} / ${productionBatches.length-completed}`}/><Kpi icon={<Clock3 size={16}/>} label={t("Wyprodukowano dobrych")} value={`${formatNumber(totalGood,0,lang)} ${t("szt.")}`}/><Kpi icon={<span className="font-bold">%</span>} label={t("Brakowość łączna")} value={formatPercent(totalBad/(totalGood+totalBad)*100,1,lang)}/></div>
    <div className="mb-3 grid grid-cols-[1fr_210px_190px] gap-2"><label className="flex items-center gap-2 border border-(--color-border-strong) bg-white px-3"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("Szarża, zlecenie, partia lub operator…")} className="h-9 w-full bg-transparent text-[11px] outline-none"/></label><select value={productId} onChange={e=>setProductId(e.target.value)} className="border border-(--color-border-strong) bg-white px-3 text-[11px]"><option value="all">{t("Wszystkie wyroby")}</option>{["P-101","P-102","P-103","P-104","P-105","P-106"].map(id=><option key={id} value={id}>{id} · {t(getProduct(id).name)}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="border border-(--color-border-strong) bg-white px-3 text-[11px]"><option value="all">{t("Wszystkie statusy")}</option><option value="zakonczona">{t("Zakończone")}</option><option value="w_realizacji">{t("W realizacji")}</option><option value="wstrzymana">{t("Wstrzymane")}</option></select></div>
    <div className="grid grid-cols-[490px_1fr] gap-4"><div className="max-h-[650px] overflow-auto border border-(--color-border) bg-white"><table className="w-full text-[9.5px]"><thead className="sticky top-0 bg-(--color-bg) uppercase text-(--color-ink-faint)"><tr><th className="p-2 text-left">{t("Szarża / data")}</th><th>{t("Wyrób")}</th><th>{t("Maszyna")}</th><th>{t("Dobre")}</th><th>{t("Braki")}</th><th>{t("Status")}</th></tr></thead><tbody>{filtered.map(batch=><tr key={batch.id} onClick={()=>setSelectedId(batch.id)} className={`cursor-pointer border-t ${selected.id===batch.id?"bg-(--color-steel-light)":"hover:bg-(--color-bg)"}`}><td className="p-2"><b className="font-mono">{batch.id}</b><div className="text-[8.5px] text-(--color-ink-faint)">{batch.startedAt.replace("T"," ")} · {t("zm.")} {batch.shift}</div></td><td className="text-center font-mono">{batch.productId}</td><td className="text-center font-mono">{batch.machineId}</td><td className="text-center font-mono">{formatNumber(batch.goodQty,0,lang)}</td><td className="text-center font-mono text-(--color-status-red)">{formatNumber(batch.badQty,0,lang)}</td><td className="text-center"><span className={`rounded-sm px-1 py-0.5 text-[7.5px] font-bold ${batch.status==="zakonczona"?"bg-(--color-status-green-bg) text-(--color-status-green)":batch.status==="wstrzymana"?"bg-(--color-status-red-bg) text-(--color-status-red)":"bg-(--color-status-amber-bg) text-(--color-status-amber)"}`}>{t(statusLabel[batch.status])}</span></td></tr>)}</tbody></table></div><BatchDetails batch={selected}/></div>
  </div>;
}
function BatchDetails({batch}:{batch:ProductionBatch}) {
  const t=useT(); const lang=useLang();
  const processed=batch.goodQty+batch.badQty; const scrap=processed?batch.badQty/processed*100:0;
  return <DocumentSheet meta={{id:`DOC-${batch.id}`,symbol:"ZP",number:batch.id,moduleId:2,author:batch.operator,authorRole:"operator",date:batch.startedAt,status:batch.status==="zakonczona"?"zatwierdzony":"zlozony",shift:batch.shift,relatedOrderId:batch.productionOrderId}} title={t("Karta szarży produkcyjnej")}><div className="grid grid-cols-2 gap-x-4"><DocumentField label={t("Wyrób")} value={`${batch.productId} · ${t(getProduct(batch.productId).name)}`}/><DocumentField label={t("Status szarży")} value={t(statusLabel[batch.status])}/><DocumentField label={t("Zlecenie")} value={batch.productionOrderId}/><DocumentField label={t("Maszyna / forma")} value={`${batch.machineId} / ${batch.moldId}`}/><DocumentField label={t("Start")} value={batch.startedAt.replace("T"," ")}/><DocumentField label={t("Koniec")} value={batch.finishedAt?.replace("T"," ")??"—"}/><DocumentField label={t("Operator / nastawiacz")} value={`${batch.operator} / ${batch.setter}`}/><DocumentField label={t("Zmiana")} value={batch.shift}/><DocumentField label={t("Partia surowca")} value={batch.materialLot}/><DocumentField label={t("Partia barwnika")} value={batch.colorantLot}/><DocumentField label={t("Plan / dobre")} value={`${formatNumber(batch.plannedQty,0,lang)} / ${formatNumber(batch.goodQty,0,lang)} ${t("szt.")}`}/><DocumentField label={t("Wadliwe / brakowość")} value={`${formatNumber(batch.badQty,0,lang)} / ${formatPercent(scrap,1,lang)}`}/><DocumentField label={t("Cykl rzeczywisty")} value={`${batch.actualCycleTimeS} s`}/><DocumentField label={t("Kontrola jakości")} value={t(batch.qualityStatus.toUpperCase())}/><DocumentField label={t("Raport źródłowy")} value={batch.shiftReportNumber} source={batch.shiftReportNumber}/></div><div className="mt-4 border border-(--color-border) bg-(--color-bg) p-3 text-[10.5px] text-(--color-ink-soft)">{t("Pełna identyfikowalność: wyrób → zlecenie → szarża → partie materiałów → maszyna i forma → operator → raport zmianowy.")}</div></DocumentSheet>;
}
function Kpi({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="flex items-center gap-3 border border-(--color-border) bg-white p-3"><span className="text-(--color-steel)">{icon}</span><div><div className="text-[9px] font-bold uppercase text-(--color-ink-faint)">{label}</div><div className="font-mono text-[17px] font-bold text-(--color-navy)">{value}</div></div></div>}
