import type { Material, Machine, Product, ProductionOrder } from "./types";

export const materials: Material[] = [
  { id: "M1", symbol: "TPE-S 4055", type: "tworzywo", priceZlKg: 18.0 },
  { id: "M2", symbol: "PP H734-52", type: "tworzywo", priceZlKg: 6.2 },
  { id: "M3", symbol: "POM C9021", type: "tworzywo", priceZlKg: 11.8 },
  { id: "M4", symbol: "Masterbatch UNI", type: "barwnik", priceZlKg: 42.0 },
  { id: "M5", symbol: "Masterbatch ECO", type: "barwnik", priceZlKg: 38.0 },
  { id: "M6", symbol: "Masterbatch TECH", type: "barwnik", priceZlKg: 45.0 },
];

export const machines: Machine[] = [
  { id: "W1", name: "Engel 80T", rateZlH: 78.0 },
  { id: "W2", name: "Arburg 100T", rateZlH: 82.0 },
  { id: "W3", name: "Haitian 120T", rateZlH: 88.0 },
  { id: "W4", name: "Engel 180T", rateZlH: 95.0 },
  { id: "W5", name: "Haitian 250T", rateZlH: 110.0 },
  { id: "W6", name: "Engel 400T", rateZlH: 135.0 },
];

export const products: Product[] = [
  {
    id: "P-101",
    name: "Miska dla psa 900 ml",
    weightNetG: 96.0,
    weightGrossG: 104.0,
    cavities: 1,
    cycleTimeS: 48,
    recipe: [{ materialId: "M2", share: 1.0 }],
    colorantId: "M5",
    colorantDosagePct: 2.0,
    machineId: "W5",
    scrapRatePct: 2.5,
    priceZl: 3.2,
  },
  {
    id: "P-102",
    name: "Szarpak Rope",
    weightNetG: 42.0,
    weightGrossG: 48.0,
    cavities: 2,
    cycleTimeS: 38,
    recipe: [
      { materialId: "M1", share: 0.9 },
      { materialId: "M2", share: 0.1 },
    ],
    colorantId: "M4",
    colorantDosagePct: 3.0,
    machineId: "W4",
    scrapRatePct: 5.0,
    priceZl: 1.95,
    colors: ["zielony", "czerwony", "niebieski", "żółty", "czarny"],
  },
  {
    id: "P-103",
    name: "Gryzak kość mały",
    weightNetG: 11.0,
    weightGrossG: 13.5,
    cavities: 4,
    cycleTimeS: 22,
    recipe: [{ materialId: "M1", share: 1.0 }],
    colorantId: "M4",
    colorantDosagePct: 2.5,
    machineId: "W2",
    scrapRatePct: 3.5,
    priceZl: 0.52,
  },
  {
    id: "P-104",
    name: "Klips do smyczy",
    weightNetG: 3.1,
    weightGrossG: 3.9,
    cavities: 16,
    cycleTimeS: 11,
    recipe: [{ materialId: "M3", share: 1.0 }],
    colorantId: "M6",
    colorantDosagePct: 1.5,
    machineId: "W3",
    scrapRatePct: 4.0,
    priceZl: 0.088,
  },
  {
    id: "P-105",
    name: "Rączka RAIS 2 – elastomer",
    weightNetG: 18.0,
    weightGrossG: 22.0,
    cavities: 2,
    cycleTimeS: 32,
    recipe: [
      { materialId: "M1", share: 0.9 },
      { materialId: "M2", share: 0.1 },
    ],
    colorantId: "M4",
    colorantDosagePct: 2.5,
    machineId: "W4",
    scrapRatePct: 3.0,
    priceZl: 1.15,
  },
  {
    id: "P-106",
    name: "Pokrywa kuwety maxi",
    weightNetG: 185.0,
    weightGrossG: 198.0,
    cavities: 1,
    cycleTimeS: 72,
    recipe: [{ materialId: "M2", share: 1.0 }],
    colorantId: "M5",
    colorantDosagePct: 1.8,
    machineId: "W6",
    scrapRatePct: 2.0,
    priceZl: 6.4,
  },
];

export const productionOrders: ProductionOrder[] = [
  {
    id: "ZP/2026/218",
    productId: "P-105",
    orderedQty: 5000,
    goodQty: 4720,
    actualCycleTimeS: 39,
    actualScrapRatePct: 14.0,
    actualMaterialPriceOverrides: { M1: 19.4 },
    setupTimeH: 4.5,
    date: "2026-06-15",
  },
  {
    id: "ZP/2026/221",
    productId: "P-102",
    orderedQty: 5000,
    goodQty: 4850,
    actualCycleTimeS: 41,
    actualScrapRatePct: 7.5,
    actualMaterialPriceOverrides: { M1: 19.4 },
    setupTimeH: 3.0,
    date: "2026-06-22",
  },
  {
    id: "ZP/2026/224",
    productId: "P-104",
    orderedQty: 20000,
    goodQty: 19600,
    actualCycleTimeS: 11,
    actualScrapRatePct: 4.5,
    setupTimeH: 2.0,
    date: "2026-06-29",
  },
];

export const operators = ["J. Kowalski", "M. Nowak", "A. Wiśniewska", "T. Zieliński"];
